<option value="" data-icon=""></option>
<option value="fa fa-glass" data-icon="fa fa-glass">glass</option>
<option value="fa fa-music" data-icon="fa fa-music">music</option>
<option value="fa fa-search" data-icon="fa fa-search">search</option>
<option value="fa fa-envelope-o" data-icon="fa fa-envelope-o">envelope-o</option>
<option value="fa fa-heart" data-icon="fa fa-heart">heart</option>
<option value="fa fa-star" data-icon="fa fa-star">star</option>
<option value="fa fa-star-o" data-icon="fa fa-star-o">star-o</option>
<option value="fa fa-user" data-icon="fa fa-user">user</option>
<option value="fa fa-film" data-icon="fa fa-film">film</option>
<option value="fa fa-th-large" data-icon="fa fa-th-large">th-large</option>
<option value="fa fa-th" data-icon="fa fa-th">th</option>
<option value="fa fa-th-list" data-icon="fa fa-th-list">th-list</option>
<option value="fa fa-check" data-icon="fa fa-check">check</option>
<option value="fa fa-times" data-icon="fa fa-times">times</option>
<option value="fa fa-search-plus" data-icon="fa fa-search-plus">search-plus</option>
<option value="fa fa-search-minus" data-icon="fa fa-search-minus">search-minus</option>
<option value="fa fa-power-off" data-icon="fa fa-power-off">power-off</option>
<option value="fa fa-signal" data-icon="fa fa-signal">signal</option>
<option value="fa fa-cog" data-icon="fa fa-cog">cog</option>
<option value="fa fa-trash-o" data-icon="fa fa-trash-o">trash-o</option>
<option value="fa fa-home" data-icon="fa fa-home">home</option>
<option value="fa fa-file-o" data-icon="fa fa-file-o">file-o</option>
<option value="fa fa-clock-o" data-icon="fa fa-clock-o">clock-o</option>
<option value="fa fa-road" data-icon="fa fa-road">road</option>
<option value="fa fa-download" data-icon="fa fa-download">download</option>
<option value="fa fa-arrow-circle-o-down" data-icon="fa fa-arrow-circle-o-down">arrow-circle-o-down</option>
<option value="fa fa-arrow-circle-o-up" data-icon="fa fa-arrow-circle-o-up">arrow-circle-o-up</option>
<option value="fa fa-inbox" data-icon="fa fa-inbox">inbox</option>
<option value="fa fa-play-circle-o" data-icon="fa fa-play-circle-o">play-circle-o</option>
<option value="fa fa-repeat" data-icon="fa fa-repeat">repeat</option>
<option value="fa fa-refresh" data-icon="fa fa-refresh">refresh</option>
<option value="fa fa-list-alt" data-icon="fa fa-list-alt">list-alt</option>
<option value="fa fa-lock" data-icon="fa fa-lock">lock</option>
<option value="fa fa-flag" data-icon="fa fa-flag">flag</option>
<option value="fa fa-headphones" data-icon="fa fa-headphones">headphones</option>
<option value="fa fa-volume-off" data-icon="fa fa-volume-off">volume-off</option>
<option value="fa fa-volume-down" data-icon="fa fa-volume-down">volume-down</option>
<option value="fa fa-volume-up" data-icon="fa fa-volume-up">volume-up</option>
<option value="fa fa-qrcode" data-icon="fa fa-qrcode">qrcode</option>
<option value="fa fa-barcode" data-icon="fa fa-barcode">barcode</option>
<option value="fa fa-tag" data-icon="fa fa-tag">tag</option>
<option value="fa fa-tags" data-icon="fa fa-tags">tags</option>
<option value="fa fa-book" data-icon="fa fa-book">book</option>
<option value="fa fa-bookmark" data-icon="fa fa-bookmark">bookmark</option>
<option value="fa fa-print" data-icon="fa fa-print">print</option>
<option value="fa fa-camera" data-icon="fa fa-camera">camera</option>
<option value="fa fa-font" data-icon="fa fa-font">font</option>
<option value="fa fa-bold" data-icon="fa fa-bold">bold</option>
<option value="fa fa-italic" data-icon="fa fa-italic">italic</option>
<option value="fa fa-text-height" data-icon="fa fa-text-height">text-height</option>
<option value="fa fa-text-width" data-icon="fa fa-text-width">text-width</option>
<option value="fa fa-align-left" data-icon="fa fa-align-left">align-left</option>
<option value="fa fa-align-center" data-icon="fa fa-align-center">align-center</option>
<option value="fa fa-align-right" data-icon="fa fa-align-right">align-right</option>
<option value="fa fa-align-justify" data-icon="fa fa-align-justify">align-justify</option>
<option value="fa fa-list" data-icon="fa fa-list">list</option>
<option value="fa fa-outdent" data-icon="fa fa-outdent">outdent</option>
<option value="fa fa-indent" data-icon="fa fa-indent">indent</option>
<option value="fa fa-video-camera" data-icon="fa fa-video-camera">video-camera</option>
<option value="fa fa-picture-o" data-icon="fa fa-picture-o">picture-o</option>
<option value="fa fa-pencil" data-icon="fa fa-pencil">pencil</option>
<option value="fa fa-map-marker" data-icon="fa fa-map-marker">map-marker</option>
<option value="fa fa-adjust" data-icon="fa fa-adjust">adjust</option>
<option value="fa fa-tint" data-icon="fa fa-tint">tint</option>
<option value="fa fa-pencil-square-o" data-icon="fa fa-pencil-square-o">pencil-square-o</option>
<option value="fa fa-share-square-o" data-icon="fa fa-share-square-o">share-square-o</option>
<option value="fa fa-check-square-o" data-icon="fa fa-check-square-o">check-square-o</option>
<option value="fa fa-arrows" data-icon="fa fa-arrows">arrows</option>
<option value="fa fa-step-backward" data-icon="fa fa-step-backward">step-backward</option>
<option value="fa fa-fast-backward" data-icon="fa fa-fast-backward">fast-backward</option>
<option value="fa fa-backward" data-icon="fa fa-backward">backward</option>
<option value="fa fa-play" data-icon="fa fa-play">play</option>
<option value="fa fa-pause" data-icon="fa fa-pause">pause</option>
<option value="fa fa-stop" data-icon="fa fa-stop">stop</option>
<option value="fa fa-forward" data-icon="fa fa-forward">forward</option>
<option value="fa fa-fast-forward" data-icon="fa fa-fast-forward">fast-forward</option>
<option value="fa fa-step-forward" data-icon="fa fa-step-forward">step-forward</option>
<option value="fa fa-eject" data-icon="fa fa-eject">eject</option>
<option value="fa fa-chevron-left" data-icon="fa fa-chevron-left">chevron-left</option>
<option value="fa fa-chevron-right" data-icon="fa fa-chevron-right">chevron-right</option>
<option value="fa fa-plus-circle" data-icon="fa fa-plus-circle">plus-circle</option>
<option value="fa fa-minus-circle" data-icon="fa fa-minus-circle">minus-circle</option>
<option value="fa fa-times-circle" data-icon="fa fa-times-circle">times-circle</option>
<option value="fa fa-check-circle" data-icon="fa fa-check-circle">check-circle</option>
<option value="fa fa-question-circle" data-icon="fa fa-question-circle">question-circle</option>
<option value="fa fa-info-circle" data-icon="fa fa-info-circle">info-circle</option>
<option value="fa fa-crosshairs" data-icon="fa fa-crosshairs">crosshairs</option>
<option value="fa fa-times-circle-o" data-icon="fa fa-times-circle-o">times-circle-o</option>
<option value="fa fa-check-circle-o" data-icon="fa fa-check-circle-o">check-circle-o</option>
<option value="fa fa-ban" data-icon="fa fa-ban">ban</option>
<option value="fa fa-arrow-left" data-icon="fa fa-arrow-left">arrow-left</option>
<option value="fa fa-arrow-right" data-icon="fa fa-arrow-right">arrow-right</option>
<option value="fa fa-arrow-up" data-icon="fa fa-arrow-up">arrow-up</option>
<option value="fa fa-arrow-down" data-icon="fa fa-arrow-down">arrow-down</option>
<option value="fa fa-share" data-icon="fa fa-share">share</option>
<option value="fa fa-expand" data-icon="fa fa-expand">expand</option>
<option value="fa fa-compress" data-icon="fa fa-compress">compress</option>
<option value="fa fa-plus" data-icon="fa fa-plus">plus</option>
<option value="fa fa-minus" data-icon="fa fa-minus">minus</option>
<option value="fa fa-asterisk" data-icon="fa fa-asterisk">asterisk</option>
<option value="fa fa-exclamation-circle" data-icon="fa fa-exclamation-circle">exclamation-circle</option>
<option value="fa fa-gift" data-icon="fa fa-gift">gift</option>
<option value="fa fa-leaf" data-icon="fa fa-leaf">leaf</option>
<option value="fa fa-fire" data-icon="fa fa-fire">fire</option>
<option value="fa fa-eye" data-icon="fa fa-eye">eye</option>
<option value="fa fa-eye-slash" data-icon="fa fa-eye-slash">eye-slash</option>
<option value="fa fa-exclamation-triangle" data-icon="fa fa-exclamation-triangle">exclamation-triangle</option>
<option value="fa fa-plane" data-icon="fa fa-plane">plane</option>
<option value="fa fa-calendar" data-icon="fa fa-calendar">calendar</option>
<option value="fa fa-random" data-icon="fa fa-random">random</option>
<option value="fa fa-comment" data-icon="fa fa-comment">comment</option>
<option value="fa fa-magnet" data-icon="fa fa-magnet">magnet</option>
<option value="fa fa-chevron-up" data-icon="fa fa-chevron-up">chevron-up</option>
<option value="fa fa-chevron-down" data-icon="fa fa-chevron-down">chevron-down</option>
<option value="fa fa-retweet" data-icon="fa fa-retweet">retweet</option>
<option value="fa fa-shopping-cart" data-icon="fa fa-shopping-cart">shopping-cart</option>
<option value="fa fa-folder" data-icon="fa fa-folder">folder</option>
<option value="fa fa-folder-open" data-icon="fa fa-folder-open">folder-open</option>
<option value="fa fa-arrows-v" data-icon="fa fa-arrows-v">arrows-v</option>
<option value="fa fa-arrows-h" data-icon="fa fa-arrows-h">arrows-h</option>
<option value="fa fa-bar-chart" data-icon="fa fa-bar-chart">bar-chart</option>
<option value="fa fa-twitter-square" data-icon="fa fa-twitter-square">twitter-square</option>
<option value="fa fa-facebook-square" data-icon="fa fa-facebook-square">facebook-square</option>
<option value="fa fa-camera-retro" data-icon="fa fa-camera-retro">camera-retro</option>
<option value="fa fa-key" data-icon="fa fa-key">key</option>
<option value="fa fa-cogs" data-icon="fa fa-cogs">cogs</option>
<option value="fa fa-comments" data-icon="fa fa-comments">comments</option>
<option value="fa fa-thumbs-o-up" data-icon="fa fa-thumbs-o-up">thumbs-o-up</option>
<option value="fa fa-thumbs-o-down" data-icon="fa fa-thumbs-o-down">thumbs-o-down</option>
<option value="fa fa-star-half" data-icon="fa fa-star-half">star-half</option>
<option value="fa fa-heart-o" data-icon="fa fa-heart-o">heart-o</option>
<option value="fa fa-sign-out" data-icon="fa fa-sign-out">sign-out</option>
<option value="fa fa-linkedin-square" data-icon="fa fa-linkedin-square">linkedin-square</option>
<option value="fa fa-thumb-tack" data-icon="fa fa-thumb-tack">thumb-tack</option>
<option value="fa fa-external-link" data-icon="fa fa-external-link">external-link</option>
<option value="fa fa-sign-in" data-icon="fa fa-sign-in">sign-in</option>
<option value="fa fa-trophy" data-icon="fa fa-trophy">trophy</option>
<option value="fa fa-github-square" data-icon="fa fa-github-square">github-square</option>
<option value="fa fa-upload" data-icon="fa fa-upload">upload</option>
<option value="fa fa-lemon-o" data-icon="fa fa-lemon-o">lemon-o</option>
<option value="fa fa-phone" data-icon="fa fa-phone">phone</option>
<option value="fa fa-square-o" data-icon="fa fa-square-o">square-o</option>
<option value="fa fa-bookmark-o" data-icon="fa fa-bookmark-o">bookmark-o</option>
<option value="fa fa-phone-square" data-icon="fa fa-phone-square">phone-square</option>
<option value="fa fa-twitter" data-icon="fa fa-twitter">twitter</option>
<option value="fa fa-facebook" data-icon="fa fa-facebook">facebook</option>
<option value="fa fa-github" data-icon="fa fa-github">github</option>
<option value="fa fa-unlock" data-icon="fa fa-unlock">unlock</option>
<option value="fa fa-credit-card" data-icon="fa fa-credit-card">credit-card</option>
<option value="fa fa-rss" data-icon="fa fa-rss">rss</option>
<option value="fa fa-hdd-o" data-icon="fa fa-hdd-o">hdd-o</option>
<option value="fa fa-bullhorn" data-icon="fa fa-bullhorn">bullhorn</option>
<option value="fa fa-bell" data-icon="fa fa-bell">bell</option>
<option value="fa fa-certificate" data-icon="fa fa-certificate">certificate</option>
<option value="fa fa-hand-o-right" data-icon="fa fa-hand-o-right">hand-o-right</option>
<option value="fa fa-hand-o-left" data-icon="fa fa-hand-o-left">hand-o-left</option>
<option value="fa fa-hand-o-up" data-icon="fa fa-hand-o-up">hand-o-up</option>
<option value="fa fa-hand-o-down" data-icon="fa fa-hand-o-down">hand-o-down</option>
<option value="fa fa-arrow-circle-left" data-icon="fa fa-arrow-circle-left">arrow-circle-left</option>
<option value="fa fa-arrow-circle-right" data-icon="fa fa-arrow-circle-right">arrow-circle-right</option>
<option value="fa fa-arrow-circle-up" data-icon="fa fa-arrow-circle-up">arrow-circle-up</option>
<option value="fa fa-arrow-circle-down" data-icon="fa fa-arrow-circle-down">arrow-circle-down</option>
<option value="fa fa-globe" data-icon="fa fa-globe">globe</option>
<option value="fa fa-wrench" data-icon="fa fa-wrench">wrench</option>
<option value="fa fa-tasks" data-icon="fa fa-tasks">tasks</option>
<option value="fa fa-filter" data-icon="fa fa-filter">filter</option>
<option value="fa fa-briefcase" data-icon="fa fa-briefcase">briefcase</option>
<option value="fa fa-arrows-alt" data-icon="fa fa-arrows-alt">arrows-alt</option>
<option value="fa fa-users" data-icon="fa fa-users">users</option>
<option value="fa fa-link" data-icon="fa fa-link">link</option>
<option value="fa fa-cloud" data-icon="fa fa-cloud">cloud</option>
<option value="fa fa-flask" data-icon="fa fa-flask">flask</option>
<option value="fa fa-scissors" data-icon="fa fa-scissors">scissors</option>
<option value="fa fa-files-o" data-icon="fa fa-files-o">files-o</option>
<option value="fa fa-paperclip" data-icon="fa fa-paperclip">paperclip</option>
<option value="fa fa-floppy-o" data-icon="fa fa-floppy-o">floppy-o</option>
<option value="fa fa-square" data-icon="fa fa-square">square</option>
<option value="fa fa-bars" data-icon="fa fa-bars">bars</option>
<option value="fa fa-list-ul" data-icon="fa fa-list-ul">list-ul</option>
<option value="fa fa-list-ol" data-icon="fa fa-list-ol">list-ol</option>
<option value="fa fa-strikethrough" data-icon="fa fa-strikethrough">strikethrough</option>
<option value="fa fa-underline" data-icon="fa fa-underline">underline</option>
<option value="fa fa-table" data-icon="fa fa-table">table</option>
<option value="fa fa-magic" data-icon="fa fa-magic">magic</option>
<option value="fa fa-truck" data-icon="fa fa-truck">truck</option>
<option value="fa fa-pinterest" data-icon="fa fa-pinterest">pinterest</option>
<option value="fa fa-pinterest-square" data-icon="fa fa-pinterest-square">pinterest-square</option>
<option value="fa fa-google-plus-square" data-icon="fa fa-google-plus-square">google-plus-square</option>
<option value="fa fa-google-plus" data-icon="fa fa-google-plus">google-plus</option>
<option value="fa fa-money" data-icon="fa fa-money">money</option>
<option value="fa fa-caret-down" data-icon="fa fa-caret-down">caret-down</option>
<option value="fa fa-caret-up" data-icon="fa fa-caret-up">caret-up</option>
<option value="fa fa-caret-left" data-icon="fa fa-caret-left">caret-left</option>
<option value="fa fa-caret-right" data-icon="fa fa-caret-right">caret-right</option>
<option value="fa fa-columns" data-icon="fa fa-columns">columns</option>
<option value="fa fa-sort" data-icon="fa fa-sort">sort</option>
<option value="fa fa-sort-desc" data-icon="fa fa-sort-desc">sort-desc</option>
<option value="fa fa-sort-asc" data-icon="fa fa-sort-asc">sort-asc</option>
<option value="fa fa-envelope" data-icon="fa fa-envelope">envelope</option>
<option value="fa fa-linkedin" data-icon="fa fa-linkedin">linkedin</option>
<option value="fa fa-undo" data-icon="fa fa-undo">undo</option>
<option value="fa fa-gavel" data-icon="fa fa-gavel">gavel</option>
<option value="fa fa-tachometer" data-icon="fa fa-tachometer">tachometer</option>
<option value="fa fa-comment-o" data-icon="fa fa-comment-o">comment-o</option>
<option value="fa fa-comments-o" data-icon="fa fa-comments-o">comments-o</option>
<option value="fa fa-bolt" data-icon="fa fa-bolt">bolt</option>
<option value="fa fa-sitemap" data-icon="fa fa-sitemap">sitemap</option>
<option value="fa fa-umbrella" data-icon="fa fa-umbrella">umbrella</option>
<option value="fa fa-clipboard" data-icon="fa fa-clipboard">clipboard</option>
<option value="fa fa-lightbulb-o" data-icon="fa fa-lightbulb-o">lightbulb-o</option>
<option value="fa fa-exchange" data-icon="fa fa-exchange">exchange</option>
<option value="fa fa-cloud-download" data-icon="fa fa-cloud-download">cloud-download</option>
<option value="fa fa-cloud-upload" data-icon="fa fa-cloud-upload">cloud-upload</option>
<option value="fa fa-user-md" data-icon="fa fa-user-md">user-md</option>
<option value="fa fa-stethoscope" data-icon="fa fa-stethoscope">stethoscope</option>
<option value="fa fa-suitcase" data-icon="fa fa-suitcase">suitcase</option>
<option value="fa fa-bell-o" data-icon="fa fa-bell-o">bell-o</option>
<option value="fa fa-coffee" data-icon="fa fa-coffee">coffee</option>
<option value="fa fa-cutlery" data-icon="fa fa-cutlery">cutlery</option>
<option value="fa fa-file-text-o" data-icon="fa fa-file-text-o">file-text-o</option>
<option value="fa fa-building-o" data-icon="fa fa-building-o">building-o</option>
<option value="fa fa-hospital-o" data-icon="fa fa-hospital-o">hospital-o</option>
<option value="fa fa-ambulance" data-icon="fa fa-ambulance">ambulance</option>
<option value="fa fa-medkit" data-icon="fa fa-medkit">medkit</option>
<option value="fa fa-fighter-jet" data-icon="fa fa-fighter-jet">fighter-jet</option>
<option value="fa fa-beer" data-icon="fa fa-beer">beer</option>
<option value="fa fa-h-square" data-icon="fa fa-h-square">h-square</option>
<option value="fa fa-plus-square" data-icon="fa fa-plus-square">plus-square</option>
<option value="fa fa-angle-double-left" data-icon="fa fa-angle-double-left">angle-double-left</option>
<option value="fa fa-angle-double-right" data-icon="fa fa-angle-double-right">angle-double-right</option>
<option value="fa fa-angle-double-up" data-icon="fa fa-angle-double-up">angle-double-up</option>
<option value="fa fa-angle-double-down" data-icon="fa fa-angle-double-down">angle-double-down</option>
<option value="fa fa-angle-left" data-icon="fa fa-angle-left">angle-left</option>
<option value="fa fa-angle-right" data-icon="fa fa-angle-right">angle-right</option>
<option value="fa fa-angle-up" data-icon="fa fa-angle-up">angle-up</option>
<option value="fa fa-angle-down" data-icon="fa fa-angle-down">angle-down</option>
<option value="fa fa-desktop" data-icon="fa fa-desktop">desktop</option>
<option value="fa fa-laptop" data-icon="fa fa-laptop">laptop</option>
<option value="fa fa-tablet" data-icon="fa fa-tablet">tablet</option>
<option value="fa fa-mobile" data-icon="fa fa-mobile">mobile</option>
<option value="fa fa-circle-o" data-icon="fa fa-circle-o">circle-o</option>
<option value="fa fa-quote-left" data-icon="fa fa-quote-left">quote-left</option>
<option value="fa fa-quote-right" data-icon="fa fa-quote-right">quote-right</option>
<option value="fa fa-spinner" data-icon="fa fa-spinner">spinner</option>
<option value="fa fa-circle" data-icon="fa fa-circle">circle</option>
<option value="fa fa-reply" data-icon="fa fa-reply">reply</option>
<option value="fa fa-github-alt" data-icon="fa fa-github-alt">github-alt</option>
<option value="fa fa-folder-o" data-icon="fa fa-folder-o">folder-o</option>
<option value="fa fa-folder-open-o" data-icon="fa fa-folder-open-o">folder-open-o</option>
<option value="fa fa-smile-o" data-icon="fa fa-smile-o">smile-o</option>
<option value="fa fa-frown-o" data-icon="fa fa-frown-o">frown-o</option>
<option value="fa fa-meh-o" data-icon="fa fa-meh-o">meh-o</option>
<option value="fa fa-gamepad" data-icon="fa fa-gamepad">gamepad</option>
<option value="fa fa-keyboard-o" data-icon="fa fa-keyboard-o">keyboard-o</option>
<option value="fa fa-flag-o" data-icon="fa fa-flag-o">flag-o</option>
<option value="fa fa-flag-checkered" data-icon="fa fa-flag-checkered">flag-checkered</option>
<option value="fa fa-terminal" data-icon="fa fa-terminal">terminal</option>
<option value="fa fa-code" data-icon="fa fa-code">code</option>
<option value="fa fa-reply-all" data-icon="fa fa-reply-all">reply-all</option>
<option value="fa fa-star-half-o" data-icon="fa fa-star-half-o">star-half-o</option>
<option value="fa fa-location-arrow" data-icon="fa fa-location-arrow">location-arrow</option>
<option value="fa fa-crop" data-icon="fa fa-crop">crop</option>
<option value="fa fa-code-fork" data-icon="fa fa-code-fork">code-fork</option>
<option value="fa fa-chain-broken" data-icon="fa fa-chain-broken">chain-broken</option>
<option value="fa fa-question" data-icon="fa fa-question">question</option>
<option value="fa fa-info" data-icon="fa fa-info">info</option>
<option value="fa fa-exclamation" data-icon="fa fa-exclamation">exclamation</option>
<option value="fa fa-superscript" data-icon="fa fa-superscript">superscript</option>
<option value="fa fa-subscript" data-icon="fa fa-subscript">subscript</option>
<option value="fa fa-eraser" data-icon="fa fa-eraser">eraser</option>
<option value="fa fa-puzzle-piece" data-icon="fa fa-puzzle-piece">puzzle-piece</option>
<option value="fa fa-microphone" data-icon="fa fa-microphone">microphone</option>
<option value="fa fa-microphone-slash" data-icon="fa fa-microphone-slash">microphone-slash</option>
<option value="fa fa-shield" data-icon="fa fa-shield">shield</option>
<option value="fa fa-calendar-o" data-icon="fa fa-calendar-o">calendar-o</option>
<option value="fa fa-fire-extinguisher" data-icon="fa fa-fire-extinguisher">fire-extinguisher</option>
<option value="fa fa-rocket" data-icon="fa fa-rocket">rocket</option>
<option value="fa fa-maxcdn" data-icon="fa fa-maxcdn">maxcdn</option>
<option value="fa fa-chevron-circle-left" data-icon="fa fa-chevron-circle-left">chevron-circle-left</option>
<option value="fa fa-chevron-circle-right" data-icon="fa fa-chevron-circle-right">chevron-circle-right</option>
<option value="fa fa-chevron-circle-up" data-icon="fa fa-chevron-circle-up">chevron-circle-up</option>
<option value="fa fa-chevron-circle-down" data-icon="fa fa-chevron-circle-down">chevron-circle-down</option>
<option value="fa fa-html5" data-icon="fa fa-html5">html5</option>
<option value="fa fa-css3" data-icon="fa fa-css3">css3</option>
<option value="fa fa-anchor" data-icon="fa fa-anchor">anchor</option>
<option value="fa fa-unlock-alt" data-icon="fa fa-unlock-alt">unlock-alt</option>
<option value="fa fa-bullseye" data-icon="fa fa-bullseye">bullseye</option>
<option value="fa fa-ellipsis-h" data-icon="fa fa-ellipsis-h">ellipsis-h</option>
<option value="fa fa-ellipsis-v" data-icon="fa fa-ellipsis-v">ellipsis-v</option>
<option value="fa fa-rss-square" data-icon="fa fa-rss-square">rss-square</option>
<option value="fa fa-play-circle" data-icon="fa fa-play-circle">play-circle</option>
<option value="fa fa-ticket" data-icon="fa fa-ticket">ticket</option>
<option value="fa fa-minus-square" data-icon="fa fa-minus-square">minus-square</option>
<option value="fa fa-minus-square-o" data-icon="fa fa-minus-square-o">minus-square-o</option>
<option value="fa fa-level-up" data-icon="fa fa-level-up">level-up</option>
<option value="fa fa-level-down" data-icon="fa fa-level-down">level-down</option>
<option value="fa fa-check-square" data-icon="fa fa-check-square">check-square</option>
<option value="fa fa-pencil-square" data-icon="fa fa-pencil-square">pencil-square</option>
<option value="fa fa-external-link-square" data-icon="fa fa-external-link-square">external-link-square</option>
<option value="fa fa-share-square" data-icon="fa fa-share-square">share-square</option>
<option value="fa fa-compass" data-icon="fa fa-compass">compass</option>
<option value="fa fa-caret-square-o-down" data-icon="fa fa-caret-square-o-down">caret-square-o-down</option>
<option value="fa fa-caret-square-o-up" data-icon="fa fa-caret-square-o-up">caret-square-o-up</option>
<option value="fa fa-caret-square-o-right" data-icon="fa fa-caret-square-o-right">caret-square-o-right</option>
<option value="fa fa-eur" data-icon="fa fa-eur">eur</option>
<option value="fa fa-gbp" data-icon="fa fa-gbp">gbp</option>
<option value="fa fa-usd" data-icon="fa fa-usd">usd</option>
<option value="fa fa-inr" data-icon="fa fa-inr">inr</option>
<option value="fa fa-jpy" data-icon="fa fa-jpy">jpy</option>
<option value="fa fa-rub" data-icon="fa fa-rub">rub</option>
<option value="fa fa-krw" data-icon="fa fa-krw">krw</option>
<option value="fa fa-btc" data-icon="fa fa-btc">btc</option>
<option value="fa fa-file" data-icon="fa fa-file">file</option>
<option value="fa fa-file-text" data-icon="fa fa-file-text">file-text</option>
<option value="fa fa-sort-alpha-asc" data-icon="fa fa-sort-alpha-asc">sort-alpha-asc</option>
<option value="fa fa-sort-alpha-desc" data-icon="fa fa-sort-alpha-desc">sort-alpha-desc</option>
<option value="fa fa-sort-amount-asc" data-icon="fa fa-sort-amount-asc">sort-amount-asc</option>
<option value="fa fa-sort-amount-desc" data-icon="fa fa-sort-amount-desc">sort-amount-desc</option>
<option value="fa fa-sort-numeric-asc" data-icon="fa fa-sort-numeric-asc">sort-numeric-asc</option>
<option value="fa fa-sort-numeric-desc" data-icon="fa fa-sort-numeric-desc">sort-numeric-desc</option>
<option value="fa fa-thumbs-up" data-icon="fa fa-thumbs-up">thumbs-up</option>
<option value="fa fa-thumbs-down" data-icon="fa fa-thumbs-down">thumbs-down</option>
<option value="fa fa-youtube-square" data-icon="fa fa-youtube-square">youtube-square</option>
<option value="fa fa-youtube" data-icon="fa fa-youtube">youtube</option>
<option value="fa fa-xing" data-icon="fa fa-xing">xing</option>
<option value="fa fa-xing-square" data-icon="fa fa-xing-square">xing-square</option>
<option value="fa fa-youtube-play" data-icon="fa fa-youtube-play">youtube-play</option>
<option value="fa fa-dropbox" data-icon="fa fa-dropbox">dropbox</option>
<option value="fa fa-stack-overflow" data-icon="fa fa-stack-overflow">stack-overflow</option>
<option value="fa fa-instagram" data-icon="fa fa-instagram">instagram</option>
<option value="fa fa-flickr" data-icon="fa fa-flickr">flickr</option>
<option value="fa fa-adn" data-icon="fa fa-adn">adn</option>
<option value="fa fa-bitbucket" data-icon="fa fa-bitbucket">bitbucket</option>
<option value="fa fa-bitbucket-square" data-icon="fa fa-bitbucket-square">bitbucket-square</option>
<option value="fa fa-tumblr" data-icon="fa fa-tumblr">tumblr</option>
<option value="fa fa-tumblr-square" data-icon="fa fa-tumblr-square">tumblr-square</option>
<option value="fa fa-long-arrow-down" data-icon="fa fa-long-arrow-down">long-arrow-down</option>
<option value="fa fa-long-arrow-up" data-icon="fa fa-long-arrow-up">long-arrow-up</option>
<option value="fa fa-long-arrow-left" data-icon="fa fa-long-arrow-left">long-arrow-left</option>
<option value="fa fa-long-arrow-right" data-icon="fa fa-long-arrow-right">long-arrow-right</option>
<option value="fa fa-apple" data-icon="fa fa-apple">apple</option>
<option value="fa fa-windows" data-icon="fa fa-windows">windows</option>
<option value="fa fa-android" data-icon="fa fa-android">android</option>
<option value="fa fa-linux" data-icon="fa fa-linux">linux</option>
<option value="fa fa-dribbble" data-icon="fa fa-dribbble">dribbble</option>
<option value="fa fa-skype" data-icon="fa fa-skype">skype</option>
<option value="fa fa-foursquare" data-icon="fa fa-foursquare">foursquare</option>
<option value="fa fa-trello" data-icon="fa fa-trello">trello</option>
<option value="fa fa-female" data-icon="fa fa-female">female</option>
<option value="fa fa-male" data-icon="fa fa-male">male</option>
<option value="fa fa-gratipay" data-icon="fa fa-gratipay">gratipay</option>
<option value="fa fa-sun-o" data-icon="fa fa-sun-o">sun-o</option>
<option value="fa fa-moon-o" data-icon="fa fa-moon-o">moon-o</option>
<option value="fa fa-archive" data-icon="fa fa-archive">archive</option>
<option value="fa fa-bug" data-icon="fa fa-bug">bug</option>
<option value="fa fa-vk" data-icon="fa fa-vk">vk</option>
<option value="fa fa-weibo" data-icon="fa fa-weibo">weibo</option>
<option value="fa fa-renren" data-icon="fa fa-renren">renren</option>
<option value="fa fa-pagelines" data-icon="fa fa-pagelines">pagelines</option>
<option value="fa fa-stack-exchange" data-icon="fa fa-stack-exchange">stack-exchange</option>
<option value="fa fa-arrow-circle-o-right" data-icon="fa fa-arrow-circle-o-right">arrow-circle-o-right</option>
<option value="fa fa-arrow-circle-o-left" data-icon="fa fa-arrow-circle-o-left">arrow-circle-o-left</option>
<option value="fa fa-caret-square-o-left" data-icon="fa fa-caret-square-o-left">caret-square-o-left</option>
<option value="fa fa-dot-circle-o" data-icon="fa fa-dot-circle-o">dot-circle-o</option>
<option value="fa fa-wheelchair" data-icon="fa fa-wheelchair">wheelchair</option>
<option value="fa fa-vimeo-square" data-icon="fa fa-vimeo-square">vimeo-square</option>
<option value="fa fa-try" data-icon="fa fa-try">try</option>
<option value="fa fa-plus-square-o" data-icon="fa fa-plus-square-o">plus-square-o</option>
<option value="fa fa-space-shuttle" data-icon="fa fa-space-shuttle">space-shuttle</option>
<option value="fa fa-slack" data-icon="fa fa-slack">slack</option>
<option value="fa fa-envelope-square" data-icon="fa fa-envelope-square">envelope-square</option>
<option value="fa fa-wordpress" data-icon="fa fa-wordpress">wordpress</option>
<option value="fa fa-openid" data-icon="fa fa-openid">openid</option>
<option value="fa fa-university" data-icon="fa fa-university">university</option>
<option value="fa fa-graduation-cap" data-icon="fa fa-graduation-cap">graduation-cap</option>
<option value="fa fa-yahoo" data-icon="fa fa-yahoo">yahoo</option>
<option value="fa fa-google" data-icon="fa fa-google">google</option>
<option value="fa fa-reddit" data-icon="fa fa-reddit">reddit</option>
<option value="fa fa-reddit-square" data-icon="fa fa-reddit-square">reddit-square</option>
<option value="fa fa-stumbleupon-circle" data-icon="fa fa-stumbleupon-circle">stumbleupon-circle</option>
<option value="fa fa-stumbleupon" data-icon="fa fa-stumbleupon">stumbleupon</option>
<option value="fa fa-delicious" data-icon="fa fa-delicious">delicious</option>
<option value="fa fa-digg" data-icon="fa fa-digg">digg</option>
<option value="fa fa-pied-piper-pp" data-icon="fa fa-pied-piper-pp">pied-piper-pp</option>
<option value="fa fa-pied-piper-alt" data-icon="fa fa-pied-piper-alt">pied-piper-alt</option>
<option value="fa fa-drupal" data-icon="fa fa-drupal">drupal</option>
<option value="fa fa-joomla" data-icon="fa fa-joomla">joomla</option>
<option value="fa fa-language" data-icon="fa fa-language">language</option>
<option value="fa fa-fax" data-icon="fa fa-fax">fax</option>
<option value="fa fa-building" data-icon="fa fa-building">building</option>
<option value="fa fa-child" data-icon="fa fa-child">child</option>
<option value="fa fa-paw" data-icon="fa fa-paw">paw</option>
<option value="fa fa-spoon" data-icon="fa fa-spoon">spoon</option>
<option value="fa fa-cube" data-icon="fa fa-cube">cube</option>
<option value="fa fa-cubes" data-icon="fa fa-cubes">cubes</option>
<option value="fa fa-behance" data-icon="fa fa-behance">behance</option>
<option value="fa fa-behance-square" data-icon="fa fa-behance-square">behance-square</option>
<option value="fa fa-steam" data-icon="fa fa-steam">steam</option>
<option value="fa fa-steam-square" data-icon="fa fa-steam-square">steam-square</option>
<option value="fa fa-recycle" data-icon="fa fa-recycle">recycle</option>
<option value="fa fa-car" data-icon="fa fa-car">car</option>
<option value="fa fa-taxi" data-icon="fa fa-taxi">taxi</option>
<option value="fa fa-tree" data-icon="fa fa-tree">tree</option>
<option value="fa fa-spotify" data-icon="fa fa-spotify">spotify</option>
<option value="fa fa-deviantart" data-icon="fa fa-deviantart">deviantart</option>
<option value="fa fa-soundcloud" data-icon="fa fa-soundcloud">soundcloud</option>
<option value="fa fa-database" data-icon="fa fa-database">database</option>
<option value="fa fa-file-pdf-o" data-icon="fa fa-file-pdf-o">file-pdf-o</option>
<option value="fa fa-file-word-o" data-icon="fa fa-file-word-o">file-word-o</option>
<option value="fa fa-file-excel-o" data-icon="fa fa-file-excel-o">file-excel-o</option>
<option value="fa fa-file-powerpoint-o" data-icon="fa fa-file-powerpoint-o">file-powerpoint-o</option>
<option value="fa fa-file-image-o" data-icon="fa fa-file-image-o">file-image-o</option>
<option value="fa fa-file-archive-o" data-icon="fa fa-file-archive-o">file-archive-o</option>
<option value="fa fa-file-audio-o" data-icon="fa fa-file-audio-o">file-audio-o</option>
<option value="fa fa-file-video-o" data-icon="fa fa-file-video-o">file-video-o</option>
<option value="fa fa-file-code-o" data-icon="fa fa-file-code-o">file-code-o</option>
<option value="fa fa-vine" data-icon="fa fa-vine">vine</option>
<option value="fa fa-codepen" data-icon="fa fa-codepen">codepen</option>
<option value="fa fa-jsfiddle" data-icon="fa fa-jsfiddle">jsfiddle</option>
<option value="fa fa-life-ring" data-icon="fa fa-life-ring">life-ring</option>
<option value="fa fa-circle-o-notch" data-icon="fa fa-circle-o-notch">circle-o-notch</option>
<option value="fa fa-rebel" data-icon="fa fa-rebel">rebel</option>
<option value="fa fa-empire" data-icon="fa fa-empire">empire</option>
<option value="fa fa-git-square" data-icon="fa fa-git-square">git-square</option>
<option value="fa fa-git" data-icon="fa fa-git">git</option>
<option value="fa fa-hacker-news" data-icon="fa fa-hacker-news">hacker-news</option>
<option value="fa fa-tencent-weibo" data-icon="fa fa-tencent-weibo">tencent-weibo</option>
<option value="fa fa-qq" data-icon="fa fa-qq">qq</option>
<option value="fa fa-weixin" data-icon="fa fa-weixin">weixin</option>
<option value="fa fa-paper-plane" data-icon="fa fa-paper-plane">paper-plane</option>
<option value="fa fa-paper-plane-o" data-icon="fa fa-paper-plane-o">paper-plane-o</option>
<option value="fa fa-history" data-icon="fa fa-history">history</option>
<option value="fa fa-circle-thin" data-icon="fa fa-circle-thin">circle-thin</option>
<option value="fa fa-header" data-icon="fa fa-header">header</option>
<option value="fa fa-paragraph" data-icon="fa fa-paragraph">paragraph</option>
<option value="fa fa-sliders" data-icon="fa fa-sliders">sliders</option>
<option value="fa fa-share-alt" data-icon="fa fa-share-alt">share-alt</option>
<option value="fa fa-share-alt-square" data-icon="fa fa-share-alt-square">share-alt-square</option>
<option value="fa fa-bomb" data-icon="fa fa-bomb">bomb</option>
<option value="fa fa-futbol-o" data-icon="fa fa-futbol-o">futbol-o</option>
<option value="fa fa-tty" data-icon="fa fa-tty">tty</option>
<option value="fa fa-binoculars" data-icon="fa fa-binoculars">binoculars</option>
<option value="fa fa-plug" data-icon="fa fa-plug">plug</option>
<option value="fa fa-slideshare" data-icon="fa fa-slideshare">slideshare</option>
<option value="fa fa-twitch" data-icon="fa fa-twitch">twitch</option>
<option value="fa fa-yelp" data-icon="fa fa-yelp">yelp</option>
<option value="fa fa-newspaper-o" data-icon="fa fa-newspaper-o">newspaper-o</option>
<option value="fa fa-wifi" data-icon="fa fa-wifi">wifi</option>
<option value="fa fa-calculator" data-icon="fa fa-calculator">calculator</option>
<option value="fa fa-paypal" data-icon="fa fa-paypal">paypal</option>
<option value="fa fa-google-wallet" data-icon="fa fa-google-wallet">google-wallet</option>
<option value="fa fa-cc-visa" data-icon="fa fa-cc-visa">cc-visa</option>
<option value="fa fa-cc-mastercard" data-icon="fa fa-cc-mastercard">cc-mastercard</option>
<option value="fa fa-cc-discover" data-icon="fa fa-cc-discover">cc-discover</option>
<option value="fa fa-cc-amex" data-icon="fa fa-cc-amex">cc-amex</option>
<option value="fa fa-cc-paypal" data-icon="fa fa-cc-paypal">cc-paypal</option>
<option value="fa fa-cc-stripe" data-icon="fa fa-cc-stripe">cc-stripe</option>
<option value="fa fa-bell-slash" data-icon="fa fa-bell-slash">bell-slash</option>
<option value="fa fa-bell-slash-o" data-icon="fa fa-bell-slash-o">bell-slash-o</option>
<option value="fa fa-trash" data-icon="fa fa-trash">trash</option>
<option value="fa fa-copyright" data-icon="fa fa-copyright">copyright</option>
<option value="fa fa-at" data-icon="fa fa-at">at</option>
<option value="fa fa-eyedropper" data-icon="fa fa-eyedropper">eyedropper</option>
<option value="fa fa-paint-brush" data-icon="fa fa-paint-brush">paint-brush</option>
<option value="fa fa-birthday-cake" data-icon="fa fa-birthday-cake">birthday-cake</option>
<option value="fa fa-area-chart" data-icon="fa fa-area-chart">area-chart</option>
<option value="fa fa-pie-chart" data-icon="fa fa-pie-chart">pie-chart</option>
<option value="fa fa-line-chart" data-icon="fa fa-line-chart">line-chart</option>
<option value="fa fa-lastfm" data-icon="fa fa-lastfm">lastfm</option>
<option value="fa fa-lastfm-square" data-icon="fa fa-lastfm-square">lastfm-square</option>
<option value="fa fa-toggle-off" data-icon="fa fa-toggle-off">toggle-off</option>
<option value="fa fa-toggle-on" data-icon="fa fa-toggle-on">toggle-on</option>
<option value="fa fa-bicycle" data-icon="fa fa-bicycle">bicycle</option>
<option value="fa fa-bus" data-icon="fa fa-bus">bus</option>
<option value="fa fa-ioxhost" data-icon="fa fa-ioxhost">ioxhost</option>
<option value="fa fa-angellist" data-icon="fa fa-angellist">angellist</option>
<option value="fa fa-cc" data-icon="fa fa-cc">cc</option>
<option value="fa fa-ils" data-icon="fa fa-ils">ils</option>
<option value="fa fa-meanpath" data-icon="fa fa-meanpath">meanpath</option>
<option value="fa fa-buysellads" data-icon="fa fa-buysellads">buysellads</option>
<option value="fa fa-connectdevelop" data-icon="fa fa-connectdevelop">connectdevelop</option>
<option value="fa fa-dashcube" data-icon="fa fa-dashcube">dashcube</option>
<option value="fa fa-forumbee" data-icon="fa fa-forumbee">forumbee</option>
<option value="fa fa-leanpub" data-icon="fa fa-leanpub">leanpub</option>
<option value="fa fa-sellsy" data-icon="fa fa-sellsy">sellsy</option>
<option value="fa fa-shirtsinbulk" data-icon="fa fa-shirtsinbulk">shirtsinbulk</option>
<option value="fa fa-simplybuilt" data-icon="fa fa-simplybuilt">simplybuilt</option>
<option value="fa fa-skyatlas" data-icon="fa fa-skyatlas">skyatlas</option>
<option value="fa fa-cart-plus" data-icon="fa fa-cart-plus">cart-plus</option>
<option value="fa fa-cart-arrow-down" data-icon="fa fa-cart-arrow-down">cart-arrow-down</option>
<option value="fa fa-diamond" data-icon="fa fa-diamond">diamond</option>
<option value="fa fa-ship" data-icon="fa fa-ship">ship</option>
<option value="fa fa-user-secret" data-icon="fa fa-user-secret">user-secret</option>
<option value="fa fa-motorcycle" data-icon="fa fa-motorcycle">motorcycle</option>
<option value="fa fa-street-view" data-icon="fa fa-street-view">street-view</option>
<option value="fa fa-heartbeat" data-icon="fa fa-heartbeat">heartbeat</option>
<option value="fa fa-venus" data-icon="fa fa-venus">venus</option>
<option value="fa fa-mars" data-icon="fa fa-mars">mars</option>
<option value="fa fa-mercury" data-icon="fa fa-mercury">mercury</option>
<option value="fa fa-transgender" data-icon="fa fa-transgender">transgender</option>
<option value="fa fa-transgender-alt" data-icon="fa fa-transgender-alt">transgender-alt</option>
<option value="fa fa-venus-double" data-icon="fa fa-venus-double">venus-double</option>
<option value="fa fa-mars-double" data-icon="fa fa-mars-double">mars-double</option>
<option value="fa fa-venus-mars" data-icon="fa fa-venus-mars">venus-mars</option>
<option value="fa fa-mars-stroke" data-icon="fa fa-mars-stroke">mars-stroke</option>
<option value="fa fa-mars-stroke-v" data-icon="fa fa-mars-stroke-v">mars-stroke-v</option>
<option value="fa fa-mars-stroke-h" data-icon="fa fa-mars-stroke-h">mars-stroke-h</option>
<option value="fa fa-neuter" data-icon="fa fa-neuter">neuter</option>
<option value="fa fa-genderless" data-icon="fa fa-genderless">genderless</option>
<option value="fa fa-facebook-official" data-icon="fa fa-facebook-official">facebook-official</option>
<option value="fa fa-pinterest-p" data-icon="fa fa-pinterest-p">pinterest-p</option>
<option value="fa fa-whatsapp" data-icon="fa fa-whatsapp">whatsapp</option>
<option value="fa fa-server" data-icon="fa fa-server">server</option>
<option value="fa fa-user-plus" data-icon="fa fa-user-plus">user-plus</option>
<option value="fa fa-user-times" data-icon="fa fa-user-times">user-times</option>
<option value="fa fa-bed" data-icon="fa fa-bed">bed</option>
<option value="fa fa-viacoin" data-icon="fa fa-viacoin">viacoin</option>
<option value="fa fa-train" data-icon="fa fa-train">train</option>
<option value="fa fa-subway" data-icon="fa fa-subway">subway</option>
<option value="fa fa-medium" data-icon="fa fa-medium">medium</option>
<option value="fa fa-y-combinator" data-icon="fa fa-y-combinator">y-combinator</option>
<option value="fa fa-optin-monster" data-icon="fa fa-optin-monster">optin-monster</option>
<option value="fa fa-opencart" data-icon="fa fa-opencart">opencart</option>
<option value="fa fa-expeditedssl" data-icon="fa fa-expeditedssl">expeditedssl</option>
<option value="fa fa-battery-full" data-icon="fa fa-battery-full">battery-full</option>
<option value="fa fa-battery-three-quarters" data-icon="fa fa-battery-three-quarters">battery-three-quarters</option>
<option value="fa fa-battery-half" data-icon="fa fa-battery-half">battery-half</option>
<option value="fa fa-battery-quarter" data-icon="fa fa-battery-quarter">battery-quarter</option>
<option value="fa fa-battery-empty" data-icon="fa fa-battery-empty">battery-empty</option>
<option value="fa fa-mouse-pointer" data-icon="fa fa-mouse-pointer">mouse-pointer</option>
<option value="fa fa-i-cursor" data-icon="fa fa-i-cursor">i-cursor</option>
<option value="fa fa-object-group" data-icon="fa fa-object-group">object-group</option>
<option value="fa fa-object-ungroup" data-icon="fa fa-object-ungroup">object-ungroup</option>
<option value="fa fa-sticky-note" data-icon="fa fa-sticky-note">sticky-note</option>
<option value="fa fa-sticky-note-o" data-icon="fa fa-sticky-note-o">sticky-note-o</option>
<option value="fa fa-cc-jcb" data-icon="fa fa-cc-jcb">cc-jcb</option>
<option value="fa fa-cc-diners-club" data-icon="fa fa-cc-diners-club">cc-diners-club</option>
<option value="fa fa-clone" data-icon="fa fa-clone">clone</option>
<option value="fa fa-balance-scale" data-icon="fa fa-balance-scale">balance-scale</option>
<option value="fa fa-hourglass-o" data-icon="fa fa-hourglass-o">hourglass-o</option>
<option value="fa fa-hourglass-start" data-icon="fa fa-hourglass-start">hourglass-start</option>
<option value="fa fa-hourglass-half" data-icon="fa fa-hourglass-half">hourglass-half</option>
<option value="fa fa-hourglass-end" data-icon="fa fa-hourglass-end">hourglass-end</option>
<option value="fa fa-hourglass" data-icon="fa fa-hourglass">hourglass</option>
<option value="fa fa-hand-rock-o" data-icon="fa fa-hand-rock-o">hand-rock-o</option>
<option value="fa fa-hand-paper-o" data-icon="fa fa-hand-paper-o">hand-paper-o</option>
<option value="fa fa-hand-scissors-o" data-icon="fa fa-hand-scissors-o">hand-scissors-o</option>
<option value="fa fa-hand-lizard-o" data-icon="fa fa-hand-lizard-o">hand-lizard-o</option>
<option value="fa fa-hand-spock-o" data-icon="fa fa-hand-spock-o">hand-spock-o</option>
<option value="fa fa-hand-pointer-o" data-icon="fa fa-hand-pointer-o">hand-pointer-o</option>
<option value="fa fa-hand-peace-o" data-icon="fa fa-hand-peace-o">hand-peace-o</option>
<option value="fa fa-trademark" data-icon="fa fa-trademark">trademark</option>
<option value="fa fa-registered" data-icon="fa fa-registered">registered</option>
<option value="fa fa-creative-commons" data-icon="fa fa-creative-commons">creative-commons</option>
<option value="fa fa-gg" data-icon="fa fa-gg">gg</option>
<option value="fa fa-gg-circle" data-icon="fa fa-gg-circle">gg-circle</option>
<option value="fa fa-tripadvisor" data-icon="fa fa-tripadvisor">tripadvisor</option>
<option value="fa fa-odnoklassniki" data-icon="fa fa-odnoklassniki">odnoklassniki</option>
<option value="fa fa-odnoklassniki-square" data-icon="fa fa-odnoklassniki-square">odnoklassniki-square</option>
<option value="fa fa-get-pocket" data-icon="fa fa-get-pocket">get-pocket</option>
<option value="fa fa-wikipedia-w" data-icon="fa fa-wikipedia-w">wikipedia-w</option>
<option value="fa fa-safari" data-icon="fa fa-safari">safari</option>
<option value="fa fa-chrome" data-icon="fa fa-chrome">chrome</option>
<option value="fa fa-firefox" data-icon="fa fa-firefox">firefox</option>
<option value="fa fa-opera" data-icon="fa fa-opera">opera</option>
<option value="fa fa-internet-explorer" data-icon="fa fa-internet-explorer">internet-explorer</option>
<option value="fa fa-television" data-icon="fa fa-television">television</option>
<option value="fa fa-contao" data-icon="fa fa-contao">contao</option>
<option value="fa fa-500px" data-icon="fa fa-500px">500px</option>
<option value="fa fa-amazon" data-icon="fa fa-amazon">amazon</option>
<option value="fa fa-calendar-plus-o" data-icon="fa fa-calendar-plus-o">calendar-plus-o</option>
<option value="fa fa-calendar-minus-o" data-icon="fa fa-calendar-minus-o">calendar-minus-o</option>
<option value="fa fa-calendar-times-o" data-icon="fa fa-calendar-times-o">calendar-times-o</option>
<option value="fa fa-calendar-check-o" data-icon="fa fa-calendar-check-o">calendar-check-o</option>
<option value="fa fa-industry" data-icon="fa fa-industry">industry</option>
<option value="fa fa-map-pin" data-icon="fa fa-map-pin">map-pin</option>
<option value="fa fa-map-signs" data-icon="fa fa-map-signs">map-signs</option>
<option value="fa fa-map-o" data-icon="fa fa-map-o">map-o</option>
<option value="fa fa-map" data-icon="fa fa-map">map</option>
<option value="fa fa-commenting" data-icon="fa fa-commenting">commenting</option>
<option value="fa fa-commenting-o" data-icon="fa fa-commenting-o">commenting-o</option>
<option value="fa fa-houzz" data-icon="fa fa-houzz">houzz</option>
<option value="fa fa-vimeo" data-icon="fa fa-vimeo">vimeo</option>
<option value="fa fa-black-tie" data-icon="fa fa-black-tie">black-tie</option>
<option value="fa fa-fonticons" data-icon="fa fa-fonticons">fonticons</option>
<option value="fa fa-reddit-alien" data-icon="fa fa-reddit-alien">reddit-alien</option>
<option value="fa fa-edge" data-icon="fa fa-edge">edge</option>
<option value="fa fa-credit-card-alt" data-icon="fa fa-credit-card-alt">credit-card-alt</option>
<option value="fa fa-codiepie" data-icon="fa fa-codiepie">codiepie</option>
<option value="fa fa-modx" data-icon="fa fa-modx">modx</option>
<option value="fa fa-fort-awesome" data-icon="fa fa-fort-awesome">fort-awesome</option>
<option value="fa fa-usb" data-icon="fa fa-usb">usb</option>
<option value="fa fa-product-hunt" data-icon="fa fa-product-hunt">product-hunt</option>
<option value="fa fa-mixcloud" data-icon="fa fa-mixcloud">mixcloud</option>
<option value="fa fa-scribd" data-icon="fa fa-scribd">scribd</option>
<option value="fa fa-pause-circle" data-icon="fa fa-pause-circle">pause-circle</option>
<option value="fa fa-pause-circle-o" data-icon="fa fa-pause-circle-o">pause-circle-o</option>
<option value="fa fa-stop-circle" data-icon="fa fa-stop-circle">stop-circle</option>
<option value="fa fa-stop-circle-o" data-icon="fa fa-stop-circle-o">stop-circle-o</option>
<option value="fa fa-shopping-bag" data-icon="fa fa-shopping-bag">shopping-bag</option>
<option value="fa fa-shopping-basket" data-icon="fa fa-shopping-basket">shopping-basket</option>
<option value="fa fa-hashtag" data-icon="fa fa-hashtag">hashtag</option>
<option value="fa fa-bluetooth" data-icon="fa fa-bluetooth">bluetooth</option>
<option value="fa fa-bluetooth-b" data-icon="fa fa-bluetooth-b">bluetooth-b</option>
<option value="fa fa-percent" data-icon="fa fa-percent">percent</option>
<option value="fa fa-gitlab" data-icon="fa fa-gitlab">gitlab</option>
<option value="fa fa-wpbeginner" data-icon="fa fa-wpbeginner">wpbeginner</option>
<option value="fa fa-wpforms" data-icon="fa fa-wpforms">wpforms</option>
<option value="fa fa-envira" data-icon="fa fa-envira">envira</option>
<option value="fa fa-universal-access" data-icon="fa fa-universal-access">universal-access</option>
<option value="fa fa-wheelchair-alt" data-icon="fa fa-wheelchair-alt">wheelchair-alt</option>
<option value="fa fa-question-circle-o" data-icon="fa fa-question-circle-o">question-circle-o</option>
<option value="fa fa-blind" data-icon="fa fa-blind">blind</option>
<option value="fa fa-audio-description" data-icon="fa fa-audio-description">audio-description</option>
<option value="fa fa-volume-control-phone" data-icon="fa fa-volume-control-phone">volume-control-phone</option>
<option value="fa fa-braille" data-icon="fa fa-braille">braille</option>
<option value="fa fa-assistive-listening-systems" data-icon="fa fa-assistive-listening-systems">assistive-listening-systems</option>
<option value="fa fa-american-sign-language-interpreting" data-icon="fa fa-american-sign-language-interpreting">american-sign-language-interpreting</option>
<option value="fa fa-deaf" data-icon="fa fa-deaf">deaf</option>
<option value="fa fa-glide" data-icon="fa fa-glide">glide</option>
<option value="fa fa-glide-g" data-icon="fa fa-glide-g">glide-g</option>
<option value="fa fa-sign-language" data-icon="fa fa-sign-language">sign-language</option>
<option value="fa fa-low-vision" data-icon="fa fa-low-vision">low-vision</option>
<option value="fa fa-viadeo" data-icon="fa fa-viadeo">viadeo</option>
<option value="fa fa-viadeo-square" data-icon="fa fa-viadeo-square">viadeo-square</option>
<option value="fa fa-snapchat" data-icon="fa fa-snapchat">snapchat</option>
<option value="fa fa-snapchat-ghost" data-icon="fa fa-snapchat-ghost">snapchat-ghost</option>
<option value="fa fa-snapchat-square" data-icon="fa fa-snapchat-square">snapchat-square</option>
<option value="fa fa-pied-piper" data-icon="fa fa-pied-piper">pied-piper</option>
<option value="fa fa-first-order" data-icon="fa fa-first-order">first-order</option>
<option value="fa fa-yoast" data-icon="fa fa-yoast">yoast</option>
<option value="fa fa-themeisle" data-icon="fa fa-themeisle">themeisle</option>
<option value="fa fa-google-plus-official" data-icon="fa fa-google-plus-official">google-plus-official</option>
<option value="fa fa-font-awesome" data-icon="fa fa-font-awesome">font-awesome</option>
<option value="fa fa-handshake-o" data-icon="fa fa-handshake-o">handshake-o</option>
<option value="fa fa-envelope-open" data-icon="fa fa-envelope-open">envelope-open</option>
<option value="fa fa-envelope-open-o" data-icon="fa fa-envelope-open-o">envelope-open-o</option>
<option value="fa fa-linode" data-icon="fa fa-linode">linode</option>
<option value="fa fa-address-book" data-icon="fa fa-address-book">address-book</option>
<option value="fa fa-address-book-o" data-icon="fa fa-address-book-o">address-book-o</option>
<option value="fa fa-address-card" data-icon="fa fa-address-card">address-card</option>
<option value="fa fa-address-card-o" data-icon="fa fa-address-card-o">address-card-o</option>
<option value="fa fa-user-circle" data-icon="fa fa-user-circle">user-circle</option>
<option value="fa fa-user-circle-o" data-icon="fa fa-user-circle-o">user-circle-o</option>
<option value="fa fa-user-o" data-icon="fa fa-user-o">user-o</option>
<option value="fa fa-id-badge" data-icon="fa fa-id-badge">id-badge</option>
<option value="fa fa-id-card" data-icon="fa fa-id-card">id-card</option>
<option value="fa fa-id-card-o" data-icon="fa fa-id-card-o">id-card-o</option>
<option value="fa fa-quora" data-icon="fa fa-quora">quora</option>
<option value="fa fa-free-code-camp" data-icon="fa fa-free-code-camp">free-code-camp</option>
<option value="fa fa-telegram" data-icon="fa fa-telegram">telegram</option>
<option value="fa fa-thermometer-full" data-icon="fa fa-thermometer-full">thermometer-full</option>
<option value="fa fa-thermometer-three-quarters" data-icon="fa fa-thermometer-three-quarters">thermometer-three-quarters</option>
<option value="fa fa-thermometer-half" data-icon="fa fa-thermometer-half">thermometer-half</option>
<option value="fa fa-thermometer-quarter" data-icon="fa fa-thermometer-quarter">thermometer-quarter</option>
<option value="fa fa-thermometer-empty" data-icon="fa fa-thermometer-empty">thermometer-empty</option>
<option value="fa fa-shower" data-icon="fa fa-shower">shower</option>
<option value="fa fa-bath" data-icon="fa fa-bath">bath</option>
<option value="fa fa-podcast" data-icon="fa fa-podcast">podcast</option>
<option value="fa fa-window-maximize" data-icon="fa fa-window-maximize">window-maximize</option>
<option value="fa fa-window-minimize" data-icon="fa fa-window-minimize">window-minimize</option>
<option value="fa fa-window-restore" data-icon="fa fa-window-restore">window-restore</option>
<option value="fa fa-window-close" data-icon="fa fa-window-close">window-close</option>
<option value="fa fa-window-close-o" data-icon="fa fa-window-close-o">window-close-o</option>
<option value="fa fa-bandcamp" data-icon="fa fa-bandcamp">bandcamp</option>
<option value="fa fa-grav" data-icon="fa fa-grav">grav</option>
<option value="fa fa-etsy" data-icon="fa fa-etsy">etsy</option>
<option value="fa fa-imdb" data-icon="fa fa-imdb">imdb</option>
<option value="fa fa-ravelry" data-icon="fa fa-ravelry">ravelry</option>
<option value="fa fa-eercast" data-icon="fa fa-eercast">eercast</option>
<option value="fa fa-microchip" data-icon="fa fa-microchip">microchip</option>
<option value="fa fa-snowflake-o" data-icon="fa fa-snowflake-o">snowflake-o</option>
<option value="fa fa-superpowers" data-icon="fa fa-superpowers">superpowers</option>
<option value="fa fa-wpexplorer" data-icon="fa fa-wpexplorer">wpexplorer</option>
<option value="fa fa-meetup" data-icon="fa fa-meetup">meetup</option>
<option value="glyphicon glyphicon-asterisk" data-icon="glyphicon glyphicon-asterisk">asterisk</option>
<option value="glyphicon glyphicon-plus" data-icon="glyphicon glyphicon-plus">plus</option>
<option value="glyphicon glyphicon-euro" data-icon="glyphicon glyphicon-euro">euro</option>
<option value="glyphicon glyphicon-eur" data-icon="glyphicon glyphicon-eur">eur</option>
<option value="glyphicon glyphicon-minus" data-icon="glyphicon glyphicon-minus">minus</option>
<option value="glyphicon glyphicon-cloud" data-icon="glyphicon glyphicon-cloud">cloud</option>
<option value="glyphicon glyphicon-envelope" data-icon="glyphicon glyphicon-envelope">envelope</option>
<option value="glyphicon glyphicon-pencil" data-icon="glyphicon glyphicon-pencil">pencil</option>
<option value="glyphicon glyphicon-glass" data-icon="glyphicon glyphicon-glass">glass</option>
<option value="glyphicon glyphicon-music" data-icon="glyphicon glyphicon-music">music</option>
<option value="glyphicon glyphicon-search" data-icon="glyphicon glyphicon-search">search</option>
<option value="glyphicon glyphicon-heart" data-icon="glyphicon glyphicon-heart">heart</option>
<option value="glyphicon glyphicon-star" data-icon="glyphicon glyphicon-star">star</option>
<option value="glyphicon glyphicon-star-empty" data-icon="glyphicon glyphicon-star-empty">star-empty</option>
<option value="glyphicon glyphicon-user" data-icon="glyphicon glyphicon-user">user</option>
<option value="glyphicon glyphicon-film" data-icon="glyphicon glyphicon-film">film</option>
<option value="glyphicon glyphicon-th-large" data-icon="glyphicon glyphicon-th-large">th-large</option>
<option value="glyphicon glyphicon-th" data-icon="glyphicon glyphicon-th">th</option>
<option value="glyphicon glyphicon-th-list" data-icon="glyphicon glyphicon-th-list">th-list</option>
<option value="glyphicon glyphicon-ok" data-icon="glyphicon glyphicon-ok">ok</option>
<option value="glyphicon glyphicon-remove" data-icon="glyphicon glyphicon-remove">remove</option>
<option value="glyphicon glyphicon-zoom-in" data-icon="glyphicon glyphicon-zoom-in">zoom-in</option>
<option value="glyphicon glyphicon-zoom-out" data-icon="glyphicon glyphicon-zoom-out">zoom-out</option>
<option value="glyphicon glyphicon-off" data-icon="glyphicon glyphicon-off">off</option>
<option value="glyphicon glyphicon-signal" data-icon="glyphicon glyphicon-signal">signal</option>
<option value="glyphicon glyphicon-cog" data-icon="glyphicon glyphicon-cog">cog</option>
<option value="glyphicon glyphicon-trash" data-icon="glyphicon glyphicon-trash">trash</option>
<option value="glyphicon glyphicon-home" data-icon="glyphicon glyphicon-home">home</option>
<option value="glyphicon glyphicon-file" data-icon="glyphicon glyphicon-file">file</option>
<option value="glyphicon glyphicon-time" data-icon="glyphicon glyphicon-time">time</option>
<option value="glyphicon glyphicon-road" data-icon="glyphicon glyphicon-road">road</option>
<option value="glyphicon glyphicon-download-alt" data-icon="glyphicon glyphicon-download-alt">download-alt</option>
<option value="glyphicon glyphicon-download" data-icon="glyphicon glyphicon-download">download</option>
<option value="glyphicon glyphicon-upload" data-icon="glyphicon glyphicon-upload">upload</option>
<option value="glyphicon glyphicon-inbox" data-icon="glyphicon glyphicon-inbox">inbox</option>
<option value="glyphicon glyphicon-play-circle" data-icon="glyphicon glyphicon-play-circle">play-circle</option>
<option value="glyphicon glyphicon-repeat" data-icon="glyphicon glyphicon-repeat">repeat</option>
<option value="glyphicon glyphicon-refresh" data-icon="glyphicon glyphicon-refresh">refresh</option>
<option value="glyphicon glyphicon-list-alt" data-icon="glyphicon glyphicon-list-alt">list-alt</option>
<option value="glyphicon glyphicon-lock" data-icon="glyphicon glyphicon-lock">lock</option>
<option value="glyphicon glyphicon-flag" data-icon="glyphicon glyphicon-flag">flag</option>
<option value="glyphicon glyphicon-headphones" data-icon="glyphicon glyphicon-headphones">headphones</option>
<option value="glyphicon glyphicon-volume-off" data-icon="glyphicon glyphicon-volume-off">volume-off</option>
<option value="glyphicon glyphicon-volume-down" data-icon="glyphicon glyphicon-volume-down">volume-down</option>
<option value="glyphicon glyphicon-volume-up" data-icon="glyphicon glyphicon-volume-up">volume-up</option>
<option value="glyphicon glyphicon-qrcode" data-icon="glyphicon glyphicon-qrcode">qrcode</option>
<option value="glyphicon glyphicon-barcode" data-icon="glyphicon glyphicon-barcode">barcode</option>
<option value="glyphicon glyphicon-tag" data-icon="glyphicon glyphicon-tag">tag</option>
<option value="glyphicon glyphicon-tags" data-icon="glyphicon glyphicon-tags">tags</option>
<option value="glyphicon glyphicon-book" data-icon="glyphicon glyphicon-book">book</option>
<option value="glyphicon glyphicon-bookmark" data-icon="glyphicon glyphicon-bookmark">bookmark</option>
<option value="glyphicon glyphicon-print" data-icon="glyphicon glyphicon-print">print</option>
<option value="glyphicon glyphicon-camera" data-icon="glyphicon glyphicon-camera">camera</option>
<option value="glyphicon glyphicon-font" data-icon="glyphicon glyphicon-font">font</option>
<option value="glyphicon glyphicon-bold" data-icon="glyphicon glyphicon-bold">bold</option>
<option value="glyphicon glyphicon-italic" data-icon="glyphicon glyphicon-italic">italic</option>
<option value="glyphicon glyphicon-text-height" data-icon="glyphicon glyphicon-text-height">text-height</option>
<option value="glyphicon glyphicon-text-width" data-icon="glyphicon glyphicon-text-width">text-width</option>
<option value="glyphicon glyphicon-align-left" data-icon="glyphicon glyphicon-align-left">align-left</option>
<option value="glyphicon glyphicon-align-center" data-icon="glyphicon glyphicon-align-center">align-center</option>
<option value="glyphicon glyphicon-align-right" data-icon="glyphicon glyphicon-align-right">align-right</option>
<option value="glyphicon glyphicon-align-justify" data-icon="glyphicon glyphicon-align-justify">align-justify</option>
<option value="glyphicon glyphicon-list" data-icon="glyphicon glyphicon-list">list</option>
<option value="glyphicon glyphicon-indent-left" data-icon="glyphicon glyphicon-indent-left">indent-left</option>
<option value="glyphicon glyphicon-indent-right" data-icon="glyphicon glyphicon-indent-right">indent-right</option>
<option value="glyphicon glyphicon-facetime-video" data-icon="glyphicon glyphicon-facetime-video">facetime-video</option>
<option value="glyphicon glyphicon-picture" data-icon="glyphicon glyphicon-picture">picture</option>
<option value="glyphicon glyphicon-map-marker" data-icon="glyphicon glyphicon-map-marker">map-marker</option>
<option value="glyphicon glyphicon-adjust" data-icon="glyphicon glyphicon-adjust">adjust</option>
<option value="glyphicon glyphicon-tint" data-icon="glyphicon glyphicon-tint">tint</option>
<option value="glyphicon glyphicon-edit" data-icon="glyphicon glyphicon-edit">edit</option>
<option value="glyphicon glyphicon-share" data-icon="glyphicon glyphicon-share">share</option>
<option value="glyphicon glyphicon-check" data-icon="glyphicon glyphicon-check">check</option>
<option value="glyphicon glyphicon-move" data-icon="glyphicon glyphicon-move">move</option>
<option value="glyphicon glyphicon-step-backward" data-icon="glyphicon glyphicon-step-backward">step-backward</option>
<option value="glyphicon glyphicon-fast-backward" data-icon="glyphicon glyphicon-fast-backward">fast-backward</option>
<option value="glyphicon glyphicon-backward" data-icon="glyphicon glyphicon-backward">backward</option>
<option value="glyphicon glyphicon-play" data-icon="glyphicon glyphicon-play">play</option>
<option value="glyphicon glyphicon-pause" data-icon="glyphicon glyphicon-pause">pause</option>
<option value="glyphicon glyphicon-stop" data-icon="glyphicon glyphicon-stop">stop</option>
<option value="glyphicon glyphicon-forward" data-icon="glyphicon glyphicon-forward">forward</option>
<option value="glyphicon glyphicon-fast-forward" data-icon="glyphicon glyphicon-fast-forward">fast-forward</option>
<option value="glyphicon glyphicon-step-forward" data-icon="glyphicon glyphicon-step-forward">step-forward</option>
<option value="glyphicon glyphicon-eject" data-icon="glyphicon glyphicon-eject">eject</option>
<option value="glyphicon glyphicon-chevron-left" data-icon="glyphicon glyphicon-chevron-left">chevron-left</option>
<option value="glyphicon glyphicon-chevron-right" data-icon="glyphicon glyphicon-chevron-right">chevron-right</option>
<option value="glyphicon glyphicon-plus-sign" data-icon="glyphicon glyphicon-plus-sign">plus-sign</option>
<option value="glyphicon glyphicon-minus-sign" data-icon="glyphicon glyphicon-minus-sign">minus-sign</option>
<option value="glyphicon glyphicon-remove-sign" data-icon="glyphicon glyphicon-remove-sign">remove-sign</option>
<option value="glyphicon glyphicon-ok-sign" data-icon="glyphicon glyphicon-ok-sign">ok-sign</option>
<option value="glyphicon glyphicon-question-sign" data-icon="glyphicon glyphicon-question-sign">question-sign</option>
<option value="glyphicon glyphicon-info-sign" data-icon="glyphicon glyphicon-info-sign">info-sign</option>
<option value="glyphicon glyphicon-screenshot" data-icon="glyphicon glyphicon-screenshot">screenshot</option>
<option value="glyphicon glyphicon-remove-circle" data-icon="glyphicon glyphicon-remove-circle">remove-circle</option>
<option value="glyphicon glyphicon-ok-circle" data-icon="glyphicon glyphicon-ok-circle">ok-circle</option>
<option value="glyphicon glyphicon-ban-circle" data-icon="glyphicon glyphicon-ban-circle">ban-circle</option>
<option value="glyphicon glyphicon-arrow-left" data-icon="glyphicon glyphicon-arrow-left">arrow-left</option>
<option value="glyphicon glyphicon-arrow-right" data-icon="glyphicon glyphicon-arrow-right">arrow-right</option>
<option value="glyphicon glyphicon-arrow-up" data-icon="glyphicon glyphicon-arrow-up">arrow-up</option>
<option value="glyphicon glyphicon-arrow-down" data-icon="glyphicon glyphicon-arrow-down">arrow-down</option>
<option value="glyphicon glyphicon-share-alt" data-icon="glyphicon glyphicon-share-alt">share-alt</option>
<option value="glyphicon glyphicon-resize-full" data-icon="glyphicon glyphicon-resize-full">resize-full</option>
<option value="glyphicon glyphicon-resize-small" data-icon="glyphicon glyphicon-resize-small">resize-small</option>
<option value="glyphicon glyphicon-exclamation-sign" data-icon="glyphicon glyphicon-exclamation-sign">exclamation-sign</option>
<option value="glyphicon glyphicon-gift" data-icon="glyphicon glyphicon-gift">gift</option>
<option value="glyphicon glyphicon-leaf" data-icon="glyphicon glyphicon-leaf">leaf</option>
<option value="glyphicon glyphicon-fire" data-icon="glyphicon glyphicon-fire">fire</option>
<option value="glyphicon glyphicon-eye-open" data-icon="glyphicon glyphicon-eye-open">eye-open</option>
<option value="glyphicon glyphicon-eye-close" data-icon="glyphicon glyphicon-eye-close">eye-close</option>
<option value="glyphicon glyphicon-warning-sign" data-icon="glyphicon glyphicon-warning-sign">warning-sign</option>
<option value="glyphicon glyphicon-plane" data-icon="glyphicon glyphicon-plane">plane</option>
<option value="glyphicon glyphicon-calendar" data-icon="glyphicon glyphicon-calendar">calendar</option>
<option value="glyphicon glyphicon-random" data-icon="glyphicon glyphicon-random">random</option>
<option value="glyphicon glyphicon-comment" data-icon="glyphicon glyphicon-comment">comment</option>
<option value="glyphicon glyphicon-magnet" data-icon="glyphicon glyphicon-magnet">magnet</option>
<option value="glyphicon glyphicon-chevron-up" data-icon="glyphicon glyphicon-chevron-up">chevron-up</option>
<option value="glyphicon glyphicon-chevron-down" data-icon="glyphicon glyphicon-chevron-down">chevron-down</option>
<option value="glyphicon glyphicon-retweet" data-icon="glyphicon glyphicon-retweet">retweet</option>
<option value="glyphicon glyphicon-shopping-cart" data-icon="glyphicon glyphicon-shopping-cart">shopping-cart</option>
<option value="glyphicon glyphicon-folder-close" data-icon="glyphicon glyphicon-folder-close">folder-close</option>
<option value="glyphicon glyphicon-folder-open" data-icon="glyphicon glyphicon-folder-open">folder-open</option>
<option value="glyphicon glyphicon-resize-vertical" data-icon="glyphicon glyphicon-resize-vertical">resize-vertical</option>
<option value="glyphicon glyphicon-resize-horizontal" data-icon="glyphicon glyphicon-resize-horizontal">resize-horizontal</option>
<option value="glyphicon glyphicon-hdd" data-icon="glyphicon glyphicon-hdd">hdd</option>
<option value="glyphicon glyphicon-bullhorn" data-icon="glyphicon glyphicon-bullhorn">bullhorn</option>
<option value="glyphicon glyphicon-bell" data-icon="glyphicon glyphicon-bell">bell</option>
<option value="glyphicon glyphicon-certificate" data-icon="glyphicon glyphicon-certificate">certificate</option>
<option value="glyphicon glyphicon-thumbs-up" data-icon="glyphicon glyphicon-thumbs-up">thumbs-up</option>
<option value="glyphicon glyphicon-thumbs-down" data-icon="glyphicon glyphicon-thumbs-down">thumbs-down</option>
<option value="glyphicon glyphicon-hand-right" data-icon="glyphicon glyphicon-hand-right">hand-right</option>
<option value="glyphicon glyphicon-hand-left" data-icon="glyphicon glyphicon-hand-left">hand-left</option>
<option value="glyphicon glyphicon-hand-up" data-icon="glyphicon glyphicon-hand-up">hand-up</option>
<option value="glyphicon glyphicon-hand-down" data-icon="glyphicon glyphicon-hand-down">hand-down</option>
<option value="glyphicon glyphicon-circle-arrow-right" data-icon="glyphicon glyphicon-circle-arrow-right">circle-arrow-right</option>
<option value="glyphicon glyphicon-circle-arrow-left" data-icon="glyphicon glyphicon-circle-arrow-left">circle-arrow-left</option>
<option value="glyphicon glyphicon-circle-arrow-up" data-icon="glyphicon glyphicon-circle-arrow-up">circle-arrow-up</option>
<option value="glyphicon glyphicon-circle-arrow-down" data-icon="glyphicon glyphicon-circle-arrow-down">circle-arrow-down</option>
<option value="glyphicon glyphicon-globe" data-icon="glyphicon glyphicon-globe">globe</option>
<option value="glyphicon glyphicon-wrench" data-icon="glyphicon glyphicon-wrench">wrench</option>
<option value="glyphicon glyphicon-tasks" data-icon="glyphicon glyphicon-tasks">tasks</option>
<option value="glyphicon glyphicon-filter" data-icon="glyphicon glyphicon-filter">filter</option>
<option value="glyphicon glyphicon-briefcase" data-icon="glyphicon glyphicon-briefcase">briefcase</option>
<option value="glyphicon glyphicon-fullscreen" data-icon="glyphicon glyphicon-fullscreen">fullscreen</option>
<option value="glyphicon glyphicon-dashboard" data-icon="glyphicon glyphicon-dashboard">dashboard</option>
<option value="glyphicon glyphicon-paperclip" data-icon="glyphicon glyphicon-paperclip">paperclip</option>
<option value="glyphicon glyphicon-heart-empty" data-icon="glyphicon glyphicon-heart-empty">heart-empty</option>
<option value="glyphicon glyphicon-link" data-icon="glyphicon glyphicon-link">link</option>
<option value="glyphicon glyphicon-phone" data-icon="glyphicon glyphicon-phone">phone</option>
<option value="glyphicon glyphicon-pushpin" data-icon="glyphicon glyphicon-pushpin">pushpin</option>
<option value="glyphicon glyphicon-usd" data-icon="glyphicon glyphicon-usd">usd</option>
<option value="glyphicon glyphicon-gbp" data-icon="glyphicon glyphicon-gbp">gbp</option>
<option value="glyphicon glyphicon-sort" data-icon="glyphicon glyphicon-sort">sort</option>
<option value="glyphicon glyphicon-sort-by-alphabet" data-icon="glyphicon glyphicon-sort-by-alphabet">sort-by-alphabet</option>
<option value="glyphicon glyphicon-sort-by-alphabet-alt" data-icon="glyphicon glyphicon-sort-by-alphabet-alt">sort-by-alphabet-alt</option>
<option value="glyphicon glyphicon-sort-by-order" data-icon="glyphicon glyphicon-sort-by-order">sort-by-order</option>
<option value="glyphicon glyphicon-sort-by-order-alt" data-icon="glyphicon glyphicon-sort-by-order-alt">sort-by-order-alt</option>
<option value="glyphicon glyphicon-sort-by-attributes" data-icon="glyphicon glyphicon-sort-by-attributes">sort-by-attributes</option>
<option value="glyphicon glyphicon-sort-by-attributes-alt" data-icon="glyphicon glyphicon-sort-by-attributes-alt">sort-by-attributes-alt</option>
<option value="glyphicon glyphicon-unchecked" data-icon="glyphicon glyphicon-unchecked">unchecked</option>
<option value="glyphicon glyphicon-expand" data-icon="glyphicon glyphicon-expand">expand</option>
<option value="glyphicon glyphicon-collapse-down" data-icon="glyphicon glyphicon-collapse-down">collapse-down</option>
<option value="glyphicon glyphicon-collapse-up" data-icon="glyphicon glyphicon-collapse-up">collapse-up</option>
<option value="glyphicon glyphicon-log-in" data-icon="glyphicon glyphicon-log-in">log-in</option>
<option value="glyphicon glyphicon-flash" data-icon="glyphicon glyphicon-flash">flash</option>
<option value="glyphicon glyphicon-log-out" data-icon="glyphicon glyphicon-log-out">log-out</option>
<option value="glyphicon glyphicon-new-window" data-icon="glyphicon glyphicon-new-window">new-window</option>
<option value="glyphicon glyphicon-record" data-icon="glyphicon glyphicon-record">record</option>
<option value="glyphicon glyphicon-save" data-icon="glyphicon glyphicon-save">save</option>
<option value="glyphicon glyphicon-open" data-icon="glyphicon glyphicon-open">open</option>
<option value="glyphicon glyphicon-saved" data-icon="glyphicon glyphicon-saved">saved</option>
<option value="glyphicon glyphicon-import" data-icon="glyphicon glyphicon-import">import</option>
<option value="glyphicon glyphicon-export" data-icon="glyphicon glyphicon-export">export</option>
<option value="glyphicon glyphicon-send" data-icon="glyphicon glyphicon-send">send</option>
<option value="glyphicon glyphicon-floppy-disk" data-icon="glyphicon glyphicon-floppy-disk">floppy-disk</option>
<option value="glyphicon glyphicon-floppy-saved" data-icon="glyphicon glyphicon-floppy-saved">floppy-saved</option>
<option value="glyphicon glyphicon-floppy-remove" data-icon="glyphicon glyphicon-floppy-remove">floppy-remove</option>
<option value="glyphicon glyphicon-floppy-save" data-icon="glyphicon glyphicon-floppy-save">floppy-save</option>
<option value="glyphicon glyphicon-floppy-open" data-icon="glyphicon glyphicon-floppy-open">floppy-open</option>
<option value="glyphicon glyphicon-credit-card" data-icon="glyphicon glyphicon-credit-card">credit-card</option>
<option value="glyphicon glyphicon-transfer" data-icon="glyphicon glyphicon-transfer">transfer</option>
<option value="glyphicon glyphicon-cutlery" data-icon="glyphicon glyphicon-cutlery">cutlery</option>
<option value="glyphicon glyphicon-header" data-icon="glyphicon glyphicon-header">header</option>
<option value="glyphicon glyphicon-compressed" data-icon="glyphicon glyphicon-compressed">compressed</option>
<option value="glyphicon glyphicon-earphone" data-icon="glyphicon glyphicon-earphone">earphone</option>
<option value="glyphicon glyphicon-phone-alt" data-icon="glyphicon glyphicon-phone-alt">phone-alt</option>
<option value="glyphicon glyphicon-tower" data-icon="glyphicon glyphicon-tower">tower</option>
<option value="glyphicon glyphicon-stats" data-icon="glyphicon glyphicon-stats">stats</option>
<option value="glyphicon glyphicon-sd-video" data-icon="glyphicon glyphicon-sd-video">sd-video</option>
<option value="glyphicon glyphicon-hd-video" data-icon="glyphicon glyphicon-hd-video">hd-video</option>
<option value="glyphicon glyphicon-subtitles" data-icon="glyphicon glyphicon-subtitles">subtitles</option>
<option value="glyphicon glyphicon-sound-stereo" data-icon="glyphicon glyphicon-sound-stereo">sound-stereo</option>
<option value="glyphicon glyphicon-sound-dolby" data-icon="glyphicon glyphicon-sound-dolby">sound-dolby</option>
<option value="glyphicon glyphicon-sound-5-1" data-icon="glyphicon glyphicon-sound-5-1">sound-5-1</option>
<option value="glyphicon glyphicon-sound-6-1" data-icon="glyphicon glyphicon-sound-6-1">sound-6-1</option>
<option value="glyphicon glyphicon-sound-7-1" data-icon="glyphicon glyphicon-sound-7-1">sound-7-1</option>
<option value="glyphicon glyphicon-copyright-mark" data-icon="glyphicon glyphicon-copyright-mark">copyright-mark</option>
<option value="glyphicon glyphicon-registration-mark" data-icon="glyphicon glyphicon-registration-mark">registration-mark</option>
<option value="glyphicon glyphicon-cloud-download" data-icon="glyphicon glyphicon-cloud-download">cloud-download</option>
<option value="glyphicon glyphicon-cloud-upload" data-icon="glyphicon glyphicon-cloud-upload">cloud-upload</option>
<option value="glyphicon glyphicon-tree-conifer" data-icon="glyphicon glyphicon-tree-conifer">tree-conifer</option>
<option value="glyphicon glyphicon-tree-deciduous" data-icon="glyphicon glyphicon-tree-deciduous">tree-deciduous</option>
<option value="glyphicon glyphicon-cd" data-icon="glyphicon glyphicon-cd">cd</option>
<option value="glyphicon glyphicon-save-file" data-icon="glyphicon glyphicon-save-file">save-file</option>
<option value="glyphicon glyphicon-open-file" data-icon="glyphicon glyphicon-open-file">open-file</option>
<option value="glyphicon glyphicon-level-up" data-icon="glyphicon glyphicon-level-up">level-up</option>
<option value="glyphicon glyphicon-copy" data-icon="glyphicon glyphicon-copy">copy</option>
<option value="glyphicon glyphicon-paste" data-icon="glyphicon glyphicon-paste">paste</option>
<option value="glyphicon glyphicon-alert" data-icon="glyphicon glyphicon-alert">alert</option>
<option value="glyphicon glyphicon-equalizer" data-icon="glyphicon glyphicon-equalizer">equalizer</option>
<option value="glyphicon glyphicon-king" data-icon="glyphicon glyphicon-king">king</option>
<option value="glyphicon glyphicon-queen" data-icon="glyphicon glyphicon-queen">queen</option>
<option value="glyphicon glyphicon-pawn" data-icon="glyphicon glyphicon-pawn">pawn</option>
<option value="glyphicon glyphicon-bishop" data-icon="glyphicon glyphicon-bishop">bishop</option>
<option value="glyphicon glyphicon-knight" data-icon="glyphicon glyphicon-knight">knight</option>
<option value="glyphicon glyphicon-baby-formula" data-icon="glyphicon glyphicon-baby-formula">baby-formula</option>
<option value="glyphicon glyphicon-tent" data-icon="glyphicon glyphicon-tent">tent</option>
<option value="glyphicon glyphicon-blackboard" data-icon="glyphicon glyphicon-blackboard">blackboard</option>
<option value="glyphicon glyphicon-bed" data-icon="glyphicon glyphicon-bed">bed</option>
<option value="glyphicon glyphicon-apple" data-icon="glyphicon glyphicon-apple">apple</option>
<option value="glyphicon glyphicon-erase" data-icon="glyphicon glyphicon-erase">erase</option>
<option value="glyphicon glyphicon-hourglass" data-icon="glyphicon glyphicon-hourglass">hourglass</option>
<option value="glyphicon glyphicon-lamp" data-icon="glyphicon glyphicon-lamp">lamp</option>
<option value="glyphicon glyphicon-duplicate" data-icon="glyphicon glyphicon-duplicate">duplicate</option>
<option value="glyphicon glyphicon-piggy-bank" data-icon="glyphicon glyphicon-piggy-bank">piggy-bank</option>
<option value="glyphicon glyphicon-scissors" data-icon="glyphicon glyphicon-scissors">scissors</option>
<option value="glyphicon glyphicon-bitcoin" data-icon="glyphicon glyphicon-bitcoin">bitcoin</option>
<option value="glyphicon glyphicon-btc" data-icon="glyphicon glyphicon-btc">btc</option>
<option value="glyphicon glyphicon-xbt" data-icon="glyphicon glyphicon-xbt">xbt</option>
<option value="glyphicon glyphicon-yen" data-icon="glyphicon glyphicon-yen">yen</option>
<option value="glyphicon glyphicon-jpy" data-icon="glyphicon glyphicon-jpy">jpy</option>
<option value="glyphicon glyphicon-ruble" data-icon="glyphicon glyphicon-ruble">ruble</option>
<option value="glyphicon glyphicon-rub" data-icon="glyphicon glyphicon-rub">rub</option>
<option value="glyphicon glyphicon-scale" data-icon="glyphicon glyphicon-scale">scale</option>
<option value="glyphicon glyphicon-ice-lolly" data-icon="glyphicon glyphicon-ice-lolly">ice-lolly</option>
<option value="glyphicon glyphicon-ice-lolly-tasted" data-icon="glyphicon glyphicon-ice-lolly-tasted">ice-lolly-tasted</option>
<option value="glyphicon glyphicon-education" data-icon="glyphicon glyphicon-education">education</option>
<option value="glyphicon glyphicon-option-horizontal" data-icon="glyphicon glyphicon-option-horizontal">option-horizontal</option>
<option value="glyphicon glyphicon-option-vertical" data-icon="glyphicon glyphicon-option-vertical">option-vertical</option>
<option value="glyphicon glyphicon-menu-hamburger" data-icon="glyphicon glyphicon-menu-hamburger">menu-hamburger</option>
<option value="glyphicon glyphicon-modal-window" data-icon="glyphicon glyphicon-modal-window">modal-window</option>
<option value="glyphicon glyphicon-oil" data-icon="glyphicon glyphicon-oil">oil</option>
<option value="glyphicon glyphicon-grain" data-icon="glyphicon glyphicon-grain">grain</option>
<option value="glyphicon glyphicon-sunglasses" data-icon="glyphicon glyphicon-sunglasses">sunglasses</option>
<option value="glyphicon glyphicon-text-size" data-icon="glyphicon glyphicon-text-size">text-size</option>
<option value="glyphicon glyphicon-text-color" data-icon="glyphicon glyphicon-text-color">text-color</option>
<option value="glyphicon glyphicon-text-background" data-icon="glyphicon glyphicon-text-background">text-background</option>
<option value="glyphicon glyphicon-object-align-top" data-icon="glyphicon glyphicon-object-align-top">object-align-top</option>
<option value="glyphicon glyphicon-object-align-bottom" data-icon="glyphicon glyphicon-object-align-bottom">object-align-bottom</option>
<option value="glyphicon glyphicon-object-align-horizontal" data-icon="glyphicon glyphicon-object-align-horizontal">object-align-horizontal</option>
<option value="glyphicon glyphicon-object-align-left" data-icon="glyphicon glyphicon-object-align-left">object-align-left</option>
<option value="glyphicon glyphicon-object-align-vertical" data-icon="glyphicon glyphicon-object-align-vertical">object-align-vertical</option>
<option value="glyphicon glyphicon-object-align-right" data-icon="glyphicon glyphicon-object-align-right">object-align-right</option>
<option value="glyphicon glyphicon-triangle-right" data-icon="glyphicon glyphicon-triangle-right">triangle-right</option>
<option value="glyphicon glyphicon-triangle-left" data-icon="glyphicon glyphicon-triangle-left">triangle-left</option>
<option value="glyphicon glyphicon-triangle-bottom" data-icon="glyphicon glyphicon-triangle-bottom">triangle-bottom</option>
<option value="glyphicon glyphicon-triangle-top" data-icon="glyphicon glyphicon-triangle-top">triangle-top</option>
<option value="glyphicon glyphicon-console" data-icon="glyphicon glyphicon-console">console</option>
<option value="glyphicon glyphicon-superscript" data-icon="glyphicon glyphicon-superscript">superscript</option>
<option value="glyphicon glyphicon-subscript" data-icon="glyphicon glyphicon-subscript">subscript</option>
<option value="glyphicon glyphicon-menu-left" data-icon="glyphicon glyphicon-menu-left">menu-left</option>
<option value="glyphicon glyphicon-menu-right" data-icon="glyphicon glyphicon-menu-right">menu-right</option>
<option value="glyphicon glyphicon-menu-up" data-icon="glyphicon glyphicon-menu-up">menu-up</option>
<option value="glyphicon glyphicon-menu-down" data-icon="glyphicon glyphicon-menu-down">menu-down</option>